set POLEMOIS_PORT=3000

set POLEMOIS_LOG_LEVEL=debug

set POLEMOIS_DB_HOST=localhost
set POLEMOIS_DB_USER=admin
set POLEMOIS_DB_SECRET=admin
set POLEMOIS_DB_SCHEMA=POLEMOIS
set POLEMOIS_DB_MAX_CONNECTIONS=POLEMOIS

nodemon ./bin/www
